version: "3"
services:
  api:
    container_name: api
    build:
      dockerfile: ./apps/api/Dockerfile
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
    volumes:
      - ./apps/api/:/app/apps/api/
  db: # TODO: Add env file
    container_name: db
    image: mongo
    logging:
      driver: "none"
    restart: always
    volumes:
      - mongodb:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=test
    #   - MONGO_INITDB_ROOT_PASSWORD=test123

volumes:
  mongodb:
